# Generated by Django 5.0.1 on 2024-01-12 13:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["complete"]},
        ),
    ]
